create or replace schema GANESH_SCHEMA;

create or replace sequence EVENTS_ID_SEQ start with 19 increment by 1 noorder;
create or replace sequence EXPENSES_ID_SEQ start with 7 increment by 1 noorder;
create or replace sequence NOTIFICATION_EMAILS_ID_SEQ start with 23 increment by 1 noorder;
create or replace sequence PAYMENT_DETAILS_ID_SEQ start with 78 increment by 1 noorder;
create or replace sequence PRASAD_SEVA_ID_SEQ start with 27 increment by 1 noorder;
create or replace sequence SPONSORSHIP_ITEMS_ID_SEQ start with 20 increment by 1 noorder;
create or replace sequence SPONSORS_ID_SEQ start with 161 increment by 1 noorder;
create or replace sequence TRANSFERS_ID_SEQ start with 4 increment by 1 noorder;
create or replace sequence COMMITTEE_MEMBERS_ID_SEQ start with 1 increment by 1 noorder;
create or replace masking policy MASK_EMAIL as (VAL VARCHAR) 
returns VARCHAR ->
CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','SYSADMIN','FULL_ACCESS_ROLE') THEN val
    ELSE CONCAT(LEFT(val, 4), '***@', SPLIT_PART(val, '@', 2))
  END
;
create or replace masking policy MASK_NAME as (VAL VARCHAR) 
returns VARCHAR ->
CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','SYSADMIN','FULL_ACCESS_ROLE') THEN val
    ELSE CONCAT(LEFT(val, 4), REPEAT('X', GREATEST(LENGTH(val) - 4, 0)))
  END
;
create or replace masking policy MASK_PHONE as (VAL VARCHAR) 
returns VARCHAR ->
CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','SYSADMIN','FULL_ACCESS_ROLE') THEN val
    ELSE CONCAT(LEFT(val, 4), 'XXXX', RIGHT(val, 2))
  END
;

create or replace TABLE EVENTS (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	TITLE VARCHAR(16777216) NOT NULL,
	EVENT_DATE DATE,
	EVENT_TIME TIME(9),
	LINK VARCHAR(16777216),
	DESCRIPTION VARCHAR(16777216),
	primary key (ID)
);
create or replace TABLE EXPENSES (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	CATEGORY VARCHAR(16777216) NOT NULL,
	SUB_CATEGORY VARCHAR(16777216) NOT NULL,
	AMOUNT NUMBER(10,2) NOT NULL,
	DATE DATE NOT NULL,
	SPENT_BY VARCHAR(16777216) NOT NULL WITH MASKING POLICY GANESH_DB.GANESH_SCHEMA.MASK_NAME,
	COMMENTS VARCHAR(16777216),
	RECEIPT_PATH VARCHAR(16777216),
	RECEIPT_BLOB BINARY(8388608),
	STATUS VARCHAR(16777216) DEFAULT 'active',
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (ID)
);
create or replace TABLE LADDU_WINNERS (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	LADDU_NUMBER NUMBER(38,0) NOT NULL,
	WINNER_NAME VARCHAR(16777216) NOT NULL,
	AMOUNT NUMBER(38,0) NOT NULL,
	primary key (ID)
);
create or replace TABLE NOTIFICATION_EMAILS (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMAIL VARCHAR(16777216) NOT NULL WITH MASKING POLICY GANESH_DB.GANESH_SCHEMA.MASK_EMAIL,
	unique (EMAIL),
	primary key (ID)
);
create or replace TABLE PAYMENT_DETAILS (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	NAME VARCHAR(16777216) NOT NULL WITH MASKING POLICY GANESH_DB.GANESH_SCHEMA.MASK_NAME,
	AMOUNT NUMBER(10,2) NOT NULL,
	DATE DATE NOT NULL,
	COMMENTS VARCHAR(16777216),
	PAYMENT_TYPE VARCHAR(16777216),
	RECIEVED_ZELLE_ACC_NAME VARCHAR(16777216),
	primary key (ID)
);
create or replace TABLE COMMITTEE_MEMBERS (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	NAME VARCHAR(16777216) NOT NULL WITH MASKING POLICY GANESH_DB.GANESH_SCHEMA.MASK_NAME,
	APARTMENT VARCHAR(16777216),
	RECIEVE_CASH_ENABLE BOOLEAN NOT NULL DEFAULT FALSE,
	primary key (ID),
	unique (NAME)
);
create or replace TABLE PRASAD_SEVA (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	SEVA_TYPE VARCHAR(16777216),
	NAMES VARCHAR(16777216) WITH MASKING POLICY GANESH_DB.GANESH_SCHEMA.MASK_NAME,
	ITEM_NAME VARCHAR(16777216),
	NUM_PEOPLE NUMBER(38,0),
	APARTMENT VARCHAR(16777216),
	SEVA_DATE DATE,
	POOJA_TIME VARCHAR(16777216),
	CREATED_BY VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	STATUS VARCHAR(16777216) DEFAULT 'active',
	primary key (ID)
);
create or replace TABLE SETTLEMENTS (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	NAME VARCHAR(16777216) NOT NULL,
	AMOUNT NUMBER(10,2) NOT NULL,
	SENT_BY VARCHAR(16777216) NOT NULL,
	COMMENTS VARCHAR(16777216),
	primary key (ID)
);
create or replace TABLE SPONSORS (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	NAME VARCHAR(16777216) NOT NULL WITH MASKING POLICY GANESH_DB.GANESH_SCHEMA.MASK_NAME,
	EMAIL VARCHAR(16777216) WITH MASKING POLICY GANESH_DB.GANESH_SCHEMA.MASK_EMAIL,
	MOBILE VARCHAR(16777216) WITH MASKING POLICY GANESH_DB.GANESH_SCHEMA.MASK_PHONE,
	APARTMENT VARCHAR(16777216) NOT NULL,
	SPONSORSHIP VARCHAR(16777216),
	DONATION NUMBER(38,0) DEFAULT 0,
	GOTHRAM VARCHAR(16777216),
	SUBMITTED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE SPONSORSHIP_ITEMS (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	ITEM VARCHAR(16777216) NOT NULL,
	AMOUNT NUMBER(38,0) NOT NULL,
	SPONSOR_LIMIT NUMBER(38,0) NOT NULL,
	IMAGE_BLOB BINARY(8388608),
	IMAGE_FILENAME VARCHAR(16777216),
	unique (ITEM),
	primary key (ID)
);
create or replace TABLE TRANSFERS (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	NAME VARCHAR(16777216) NOT NULL WITH MASKING POLICY GANESH_DB.GANESH_SCHEMA.MASK_NAME,
	PHONE VARCHAR(16777216) WITH MASKING POLICY GANESH_DB.GANESH_SCHEMA.MASK_PHONE,
	EMAIL VARCHAR(16777216),
	primary key (ID)
);
