CREATE OR REPLACE FILE FORMAT my_csv_format
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY='"'
  NULL_IF = ('NULL', 'null');

COPY INTO LADDU_WINNERS
FROM @~/restore/LADDU_WINNERS
FILE_FORMAT = my_csv_format;
  
COPY INTO EVENTS
FROM @~/restore/EVENTS
FILE_FORMAT = my_csv_format;

COPY INTO EXPENSES
FROM @~/restore/EXPENSES
FILE_FORMAT = my_csv_format;

COPY INTO NOTIFICATION_EMAILS
FROM @~/restore/NOTIFICATION_EMAILS
FILE_FORMAT = my_csv_format;

COPY INTO PAYMENT_DETAILS
FROM @~/restore/PAYMENT_DETAILS
FILE_FORMAT = my_csv_format;

COPY INTO PRASAD_SEVA
FROM @~/restore/PRASAD_SEVA
FILE_FORMAT = my_csv_format;

COPY INTO SETTLEMENTS
FROM @~/restore/SETTLEMENTS
FILE_FORMAT = my_csv_format;

COPY INTO SPONSORS
FROM @~/restore/SPONSORS
FILE_FORMAT = my_csv_format;

COPY INTO SPONSORSHIP_ITEMS
FROM @~/restore/SPONSORSHIP_ITEMS
FILE_FORMAT = my_csv_format;

COPY INTO TRANSFERS
FROM @~/restore/TRANSFERS
FILE_FORMAT = my_csv_format;
