-- EVENTS
COPY INTO @~/ganesh_exports/EVENTS/
FROM GANESH_SCHEMA.EVENTS
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' COMPRESSION=GZIP)
OVERWRITE = TRUE;

-- EXPENSES
COPY INTO @~/ganesh_exports/EXPENSES/
FROM GANESH_SCHEMA.EXPENSES
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' COMPRESSION=GZIP)
OVERWRITE = TRUE;

-- LADDU_WINNERS
COPY INTO @~/ganesh_exports/LADDU_WINNERS/
FROM GANESH_SCHEMA.LADDU_WINNERS
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' COMPRESSION=GZIP)
OVERWRITE = TRUE;

-- NOTIFICATION_EMAILS
COPY INTO @~/ganesh_exports/NOTIFICATION_EMAILS/
FROM GANESH_SCHEMA.NOTIFICATION_EMAILS
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' COMPRESSION=GZIP)
OVERWRITE = TRUE;

-- PAYMENT_DETAILS
COPY INTO @~/ganesh_exports/PAYMENT_DETAILS/
FROM GANESH_SCHEMA.PAYMENT_DETAILS
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' COMPRESSION=GZIP)
OVERWRITE = TRUE;

-- PRASAD_SEVA
COPY INTO @~/ganesh_exports/PRASAD_SEVA/
FROM GANESH_SCHEMA.PRASAD_SEVA
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' COMPRESSION=GZIP)
OVERWRITE = TRUE;

-- SETTLEMENTS
COPY INTO @~/ganesh_exports/SETTLEMENTS/
FROM GANESH_SCHEMA.SETTLEMENTS
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' COMPRESSION=GZIP)
OVERWRITE = TRUE;

-- SPONSORS
COPY INTO @~/ganesh_exports/SPONSORS/
FROM GANESH_SCHEMA.SPONSORS
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' COMPRESSION=GZIP)
OVERWRITE = TRUE;

-- SPONSORSHIP_ITEMS
COPY INTO @~/ganesh_exports/SPONSORSHIP_ITEMS/
FROM GANESH_SCHEMA.SPONSORSHIP_ITEMS
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' COMPRESSION=GZIP)
OVERWRITE = TRUE;

-- TRANSFERS
COPY INTO @~/ganesh_exports/TRANSFERS/
FROM GANESH_SCHEMA.TRANSFERS
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' COMPRESSION=GZIP)
OVERWRITE = TRUE;
